# Generated by Django 3.1.7 on 2021-03-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appointments', '0001_initial'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorappointment',
            unique_together={('doctor_id', 'appointment_id')},
        ),
    ]
